### PR TITLE
fix #54 panic on no rollup events, and #55 first block to request is genesis

### LINKED ISSUE #54: Panic if first block range have no rollup events
#### System information

version: `v0.4.0' 

#### Expected behaviour
If first range of blocks have no rollup events must try next one

#### Actual behaviour
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1612f89]

goroutine 1 [running]:
github.com/0xPolygonHermez/zkevm-synchronizer-l1/synchronizer/l1_sync.(*L1SequentialSync).SyncBlocks(0xc00043c880, {0x1c33c48, 0xc00030bf40}, 0x0)
	/home/jesteban/go/pkg/mod/github.com/0x!polygon!hermez/zkevm-synchronizer-l1@v0.3.4-0.20240527074759-5eb6f4a42ddd/synchronizer/l1_sync/l1_syncer_sequential.go:161 +0x689
github.com/0xPolygonHermez/zkevm-synchronizer-l1/synchronizer/internal.(*SynchronizerImpl).Sync(0xc0003971e0, 0x1)
	/home/jesteban/go/pkg/mod/github.com/0x!polygon!hermez/zkevm-synchronizer-l1@v0.3.4-0.20240527074759-5eb6f4a42ddd/synchronizer/internal/synchronizer_impl.go:201 +0x5b8
github.com/0xPolygonHermez/zkevm-synchronizer-l1/synchronizer.(*SynchronizerAdapter).Sync(0xc0003c0000, 0x1)
	/home/jesteban/go/pkg/mod/github.com/0x!polygon!hermez/zkevm-synchronizer-l1@v0.3.4-0.20240527074759-5eb6f4a42ddd/synchronizer/synchronizer_adapter.go:31 +0x37
main.main()
	/home/jesteban/POLYGON/src/zkevm-sync-l1/client_meu/test-zkevm-sync-l1/main.go:66 +0x37c
```

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

### PR DESCRIPTION
**Pull request by joanestebanr**
Closes #54, #55

### What does this PR do?
Fix bugs

### Reviewers

Main reviewers:

- @ToniRamirezM 
- @ARR552 
- 
Codeowner reviewers:

- @-Alice
- @-Bob

### CODE REVIEW

**Review by ToniRamirezM — APPROVED** [review]

File: synchronizer/l1_sync/l1_syncer_sequential.go [hunk 1]
```diff
@@ -131,7 +131,8 @@ func (s *L1SequentialSync) SyncBlocks(ctx context.Context, lastEthBlockSynced *s
 	if lastEthBlockSynced != nil && lastEthBlockSynced.BlockNumber > 0 {
 		fromBlock = lastEthBlockSynced.BlockNumber
 	} else {
-		fromBlock = s.cfg.GenesisBlockNumber
+		// fromBlock is the first block that we have, that the reson that we must sub 1 to genesis
```
Comment (ToniRamirezM) [inline synchronizer/l1_sync/l1_syncer_sequential.go]: Correct this comment

**Review by ToniRamirezM — CHANGES_REQUESTED** [review]

**Review by ToniRamirezM — APPROVED** [review]
